swagger: '2.0'
info:
  version: 1.0.0
  title: Shasco Baseball API
  description: A sample API that uses a sqlite database and GO.
host: baseballapi.shasco.app
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /team:
    get:
      operationId: getTeams
      description: Returns all teams
      produces:
        - application/json
      responses:
        '200':
          description: A list of teams.
          schema:
            type: array
            items:
              $ref: '#/definitions/Team'
  /player:
    get:
      operationId: getPlayers
      description: Returns all players
      produces:
        - application/json
      responses:
        '200':
          description: A list of players.
          schema:
            type: array
            items:
              $ref: '#/definitions/Player'
definitions:
  Team:
    type: object
    required:
      - id
      - abbreviation
      - fullName
      - shortName
      - franchiseName
      - clubName
      - venueId
      - venueName
      - leagueId
      - leagueName
      - divisionId
      - divisionName
    properties:
      id:
        type: integer
        format: int64
      abbreviation:
        type: string
      fullName:
        type: string
      shortName:
        type: string
      franchiseName:
        type: string
      clubName:
        type: string
      venueId:
        type: integer
        format: int64
      venueName:
        type: string
      leagueId:
        type: integer
        format: int64
      leagueName:
        type: string
      divisionId:
        type: integer
        format: int64
      divisionName:
        type: string
Player:
    type: object
    required:
      - id
      - jerseyNumber
      - fullName
      - teamId
      - positionCode
      - positionName
      - positionType
      - positionAbbreviation
      - rosterType
    properties:
      id:
        type: integer
        format: int64
      jerseyNumber:
        type: string
      fullName:
        type: string
      teamId:
        type: integer
        format: int64
      positionCode:
        type: string
      positionName:
        type: string
      positionType:
        type: string
      positionAbbreviation:
        type: string
      statusDescription:
        type: string
      rosterType:
        type: string

