swagger: '2.0'
info:
  version: 1.0.0
  title: Shasco Baseball API
  description: A sample API that uses a sqlite database and GO.
host: baseballapi.shasco.app
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /team:
    get:
      operationId: getTeams
      description: Returns all teams
      produces:
        - application/json
      responses:
        '200':
          description: A list of teams.
          schema:
            type: array
            items:
              $ref: '#/definitions/Team'
  /player:
    get:
      operationId: getPlayers
      description: Returns all players
      produces:
        - application/json
      responses:
        '200':
          description: A list of players.
          schema:
            type: array
            items:
              $ref: '#/definitions/Player'
definitions:
  Team:
    type: object
    required:
      - team_id
      - team_abbreviation
      - team_full_name
      - short_name
      - franchise_name
      - club_name
      - venue_id
      - venue_name
      - league_id
      - league_name
      - division_id
      - division_name
    properties:
      team_id:
        type: integer
        format: int64
      team_abbreviation:
        type: string
      team_full_name:
        type: string
      short_name:
        type: string
      franchise_name:
        type: string
      club_name:
        type: string
      venue_id:
        type: integer
        format: int64
      venue_name:
        type: string
      league_id:
        type: integer
        format: int64
      league_name:
        type: string
      division_id:
        type: integer
        format: int64
      division_name:
        type: string
Player:
    type: object
    required:
      - id
      - jerseyNumber
      - fullName
      - teamId
      - positionCode
      - positionName
      - positionType
      - positionAbbreviation
      - rosterType
    properties:
      id:
        type: integer
        format: int64
      jerseyNumber:
        type: string
      fullName:
        type: string
      teamId:
        type: integer
        format: int64
      positionCode:
        type: string
      positionName:
        type: string
      positionType:
        type: string
      positionAbbreviation:
        type: string
      statusDescription:
        type: string
      rosterType:
        type: string

